{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3fda2083",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "# import seaborn as sns\n",
    "import streamlit as st"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e1275194",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>ICC ODI CRICKET MEN'S WORLD CUP 2023</th>\n",
       "      <th>Unnamed: 1</th>\n",
       "      <th>Unnamed: 2</th>\n",
       "      <th>Unnamed: 3</th>\n",
       "      <th>Unnamed: 4</th>\n",
       "      <th>Unnamed: 5</th>\n",
       "      <th>Unnamed: 6</th>\n",
       "      <th>Unnamed: 7</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>POINT TABLE OF WORLD CUP 2023</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>SNO</td>\n",
       "      <td>TEAM</td>\n",
       "      <td>M</td>\n",
       "      <td>W</td>\n",
       "      <td>L</td>\n",
       "      <td>NRR</td>\n",
       "      <td>Pts</td>\n",
       "      <td>Last 5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1</td>\n",
       "      <td>IND</td>\n",
       "      <td>9</td>\n",
       "      <td>9</td>\n",
       "      <td>0</td>\n",
       "      <td>2.57</td>\n",
       "      <td>18</td>\n",
       "      <td>WWWWW</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2</td>\n",
       "      <td>SA</td>\n",
       "      <td>9</td>\n",
       "      <td>7</td>\n",
       "      <td>2</td>\n",
       "      <td>1.261</td>\n",
       "      <td>14</td>\n",
       "      <td>WLWWW</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>3</td>\n",
       "      <td>AUS</td>\n",
       "      <td>9</td>\n",
       "      <td>7</td>\n",
       "      <td>2</td>\n",
       "      <td>0.841</td>\n",
       "      <td>14</td>\n",
       "      <td>WWWWW</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>4</td>\n",
       "      <td>NZ</td>\n",
       "      <td>9</td>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>0.743</td>\n",
       "      <td>10</td>\n",
       "      <td>WLLLL</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>5</td>\n",
       "      <td>PAK</td>\n",
       "      <td>9</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "      <td>-0.199</td>\n",
       "      <td>8</td>\n",
       "      <td>LWWLL</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>6</td>\n",
       "      <td>AFG</td>\n",
       "      <td>9</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "      <td>-0.336</td>\n",
       "      <td>8</td>\n",
       "      <td>LLWWW</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>7</td>\n",
       "      <td>ENG</td>\n",
       "      <td>9</td>\n",
       "      <td>3</td>\n",
       "      <td>6</td>\n",
       "      <td>-0.572</td>\n",
       "      <td>6</td>\n",
       "      <td>WWLLL</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>8</td>\n",
       "      <td>BAN</td>\n",
       "      <td>9</td>\n",
       "      <td>2</td>\n",
       "      <td>7</td>\n",
       "      <td>-1.087</td>\n",
       "      <td>4</td>\n",
       "      <td>LWLLL</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>9</td>\n",
       "      <td>SL</td>\n",
       "      <td>9</td>\n",
       "      <td>2</td>\n",
       "      <td>7</td>\n",
       "      <td>-1.419</td>\n",
       "      <td>4</td>\n",
       "      <td>LLLLW</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>10</td>\n",
       "      <td>NED</td>\n",
       "      <td>9</td>\n",
       "      <td>2</td>\n",
       "      <td>7</td>\n",
       "      <td>-1.825</td>\n",
       "      <td>4</td>\n",
       "      <td>LLLWL</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   ICC ODI CRICKET MEN'S WORLD CUP 2023 Unnamed: 1 Unnamed: 2 Unnamed: 3  \\\n",
       "0         POINT TABLE OF WORLD CUP 2023        NaN        NaN        NaN   \n",
       "1                                   SNO       TEAM          M          W   \n",
       "2                                     1        IND          9          9   \n",
       "3                                     2         SA          9          7   \n",
       "4                                     3        AUS          9          7   \n",
       "5                                     4         NZ          9          5   \n",
       "6                                     5        PAK          9          4   \n",
       "7                                     6        AFG          9          4   \n",
       "8                                     7        ENG          9          3   \n",
       "9                                     8        BAN          9          2   \n",
       "10                                    9         SL          9          2   \n",
       "11                                   10        NED          9          2   \n",
       "\n",
       "   Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  \n",
       "0         NaN        NaN        NaN        NaN  \n",
       "1           L        NRR        Pts     Last 5  \n",
       "2           0       2.57         18      WWWWW  \n",
       "3           2      1.261         14      WLWWW  \n",
       "4           2      0.841         14      WWWWW  \n",
       "5           4      0.743         10      WLLLL  \n",
       "6           5     -0.199          8      LWWLL  \n",
       "7           5     -0.336          8      LLWWW  \n",
       "8           6     -0.572          6      WWLLL  \n",
       "9           7     -1.087          4      LWLLL  \n",
       "10          7     -1.419          4      LLLLW  \n",
       "11          7     -1.825          4      LLLWL  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.read_csv('cricket.csv')\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cb7d942d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
